create table tb_comprovante (conta_id int4 not null, data_pagamento timestamp, primary key (conta_id));
create table tb_conta (id int4 generated by default as identity, data_vencimento timestamp, estado_pagamento int4, tipo_custo int4, valor float8, empresa_id int4, primary key (id));
create table tb_empresa (id int4 generated by default as identity, nome varchar(255), prioridade int4, primary key (id));
alter table if exists tb_comprovante add constraint FKr1l59xplvsolkqpuxv2uemuh5 foreign key (conta_id) references tb_conta;
alter table if exists tb_conta add constraint FK2n8cu583fpffm1l1bve7racuc foreign key (empresa_id) references tb_empresa;
